name: Butte
on: [push]

jobs:
  build:
    name: Cargo Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: 'ls the things'
        run: ls
      - name: 'tree the things'
        run: tree ..
      - name: 'Cargo test'
        run: cargo test
